Issue #142 return dist.mat even if it is invalid
hugomflavio/actel pull request #165
Opened 2024-12-10 21:23 UTC by dsmith-unbc

Minor changes to explore(), residency(), and migration() code to keep distance matrix when it is invalid but denote it with NA instead of an actual matrix of distances. 

Once merged, this fixes issue #142

2024-12-10 23:01 UTC, hugomflavio requested changes
This looks good, I have only one question regarding the news line; have a look. I'd recommend bumping the dev version since we're adding a new news line. Added a few spaces.

2024-12-10 23:01 UTC, hugomflavio commented on R/residency.R
>          intra.array.CJS, rsp.info, dist.mat, file = resultsname)
```suggestion
    save(detections, valid.detections, spatial, deployments, arrays, movements, valid.movements,
         section.movements, status.df, last.seen, array.times, section.times, intra.array.matrices,
         residency.list, time.ratios, time.positions, global.ratios, group.ratios, efficiency,
         intra.array.CJS, rsp.info, dist.mat, file = resultsname)
```

2024-12-10 23:01 UTC, hugomflavio commented on tests/testthat/test_explore.R
> +    'movements', 'valid.movements', 'times', 'rsp.info','dist.mat')))))
```suggestion
    'movements', 'valid.movements', 'times', 'rsp.info', 'dist.mat')))))
```

2024-12-10 23:01 UTC, hugomflavio commented on NEWS.md
> +  * Distance matrix is now retained in the output of `explore()`, `residency()`, and `migration()` analysis. When the distance matrix is not available or invalid, NA will be denoted in the output. (i
> When the distance matrix is not available or invalid, NA will be denoted in the output.

Is this part right? I was hoping we'd get the actual distances matrix if it is invalid. I.e. we'd only get "NA" if no distances matrix was provided at all.

2024-12-10 23:01 UTC, hugomflavio commented on NEWS.md
> +  * Distance matrix is now retained in the output of `explore()`, `residency()`, and `migration()` analysis. When the distance matrix is not available or invalid, NA will be denoted in the output. (i
I would recommend bumping the dev version too

2024-12-10 23:52 UTC, dsmith-unbc commented on NEWS.md
> +  * Distance matrix is now retained in the output of `explore()`, `residency()`, and `migration()` analysis. When the distance matrix is not available or invalid, NA will be denoted in the output. (i
Good catch my mistake! Yes NA will be only denoted if no distance matrix was provided.

2024-12-11 00:00 UTC, hugomflavio approved these changes
Awesome stuff 👍

2024-12-12 15:50 UTC, merged